### ISSUE TITLE
At some exposure settings, black cal doesn’t work 100% correctly

### ISSUE THREAD

**Issue by skronstein** [krontech/chronos-cam-app#103]
At some exposure settings, black cal doesn’t work 100% correctly or takes multiple tries to do so. I saw the following anomalies at 1280x720 max fps:

At 294us exposure, the image showed a horizontal bar that disappeared after a second black cal.

At 96.86us exposure, the image always showed a thin horizontal bar near the bottom, even after multiple extra black cals.

**Comment by oskirby** [comment]
I think this issue is a duplicate of https://github.com/krontech/chronos-cam-app/issues/149

**Comment by skronstein** [comment]
> I think this issue is a duplicate of #149

This happened on the 1.4, so I don't think it would be.  If i'm wrong, you can leave it closed.
