### ISSUE TITLE
Sometimes cannot start a second recording

### ISSUE THREAD

**Issue by skronstein** [krontech/chronos-cam-app#109]
Starting a first recording is always possible, but sometimes the camera won't start a second recording when pressing the Record button or the red shutter button.

**Comment by oskirby** [comment]
So, I think it would be more accurate to say that the camera fails to exit playback mode when closing the playback screen. The steps to reproduce this issue appear to be as follows:

1. Boot the camera, by default this should place you on the main window.
2. Start and stop a recording by the red trigger button. The "Play" button should now be active.
3. Open the playback window, and then immediately close it.
4. The camera is now on the main window, but will be displaying the contents of the recorded video.
5. While in this state, the recording button has no effect and the video remains in play mode.
