### ISSUE TITLE
Auto power mode - camera doesn't Turn off if AC removed

### ISSUE THREAD

**Issue by skronstein** [krontech/chronos-cam-app#112]
Even if Auto Power mode is set to "Turn off if AC removed" or "Both," it doesn't turn off when AC is removed.

**Comment by sanjpm** [comment]
Output from journalctl:

Dec 10 19:34:48 chronos camApp[321]: "Failed to set parameter powerOffWhenMainsDisconnected: Unknown property 'powerOffWhenMainsDisconnected' could not be set."

**Comment by skronstein** [comment]
Possibly related:
Auto Power Mode intermittently resets to Turn On if AC Inserted https://github.com/krontech/chronos-cam-app/issues/137

**Comment by oskirby** [comment]
This may also need a fix to cam-pcUtil to correctly read the power modes back from the PMIC or you may experience some UI inconsistency in the state of the auto-power mode combo box after a reboot.

https://github.com/krontech/chronos-cli/commit/bf0fc10326eaef93590611aeeb139f8d74dbc2ff
