### ISSUE TITLE
Text overlay sometimes shows when it should be disabled

### ISSUE THREAD

**Issue by skronstein** [krontech/chronos-cam-app#128]
Also, when this happens, it often appears at the top of the screen instead of the bottom.

Edit:
To reproduce this bug:
1. If the overlay is already enabled, disable it and reboot the camera.
2. Make a recording and enter Playback mode.
When I do these steps, it appears at the top when it should be disabled.

**Comment by oskirby** [comment]
Do you have any instructions on how to reproduce this issue?

**Comment by skronstein** [comment]
To reproduce it:
1. If the overlay is already enabled, disable it and reboot the camera.
2. Make a recording and enter Playback mode.
When I do these steps, it appears at the top when it should be disabled.
