### ISSUE TITLE
Trigger delay window - slider stays highlighted after any of the % buttons are pressed

### ISSUE THREAD

**Issue by skronstein** [krontech/chronos-cam-app#31]
If any of the 0%, 50% or 100% buttons are pushed on the trigger delay screen while the slider has jog wheel focus, the slider stays highlighted and the slider handle does not move. At least the buttons do have their intended effect of changing the numbers, and these numbers are still applied correctly if the OK button is pressed while the numbers do not match up with the position of the slider.

**Comment by oskirby** [comment]
This should be a trivial change to the UI design to disable the focusability of the trigger delay slider. That way the slider will never accept focus, and it should behave consistently.
