### ISSUE TITLE
Record Mode - Segmented error

### ISSUE THREAD

**Issue by skronstein** [krontech/chronos-cam-app#45]
How to reproduce:
If the trigger is pressed more times than there are segments, the video is sometimes corrupted.  This seems to occur more often when the first and last trigger are separated by more frames than what the total length of the recording is supposed to be (eg. on a 8gb camera set to 1280x1024, first and last triggers separated by more than 4365 frames).

Symptoms:
Corrupted recordings appear 70k to  about 170k frames long, at least at 1280x1024. The first n frames look normal, where n is the total record length specified on the record mode screen. The rest of the recording is various forms of garbage, including strangely colored images and vertical lines.

**Comment by oskirby** [comment]
This is a bug in how the video pipeline processes recording segments as received by the FPGA. Segments may wrap around in the FPGA memory space and that case is not being handled correctly.
