### ISSUE TITLE
Gated burst - Trigger stops responding after multiple triggers.

### ISSUE THREAD

**Issue by oskirby** [krontech/chronos-cam-app#50]
When in gated burst mode, the FPGA appears to stop detecting trigger events after several edges are received. Stoping and restarting the recording appears to get the FPGA back into a working state.

**Comment by oskirby** [comment]
This may also explain the inconsistent gated burst operation when debounce is disabled, in which case the FPGA would often only capture a segment of exactly two frames regardless of how long the trigger signal was asserted for.

**Comment by skronstein** [comment]
AFAICT, this was fixed by the commit referenced above, 389122c.
