### ISSUE TITLE
UI to enable PMIC auto power on/off.

### ISSUE THREAD

**Issue by oskirby** [krontech/chronos-cam-app#57]
The PMIC firmware has a mode which can automatically power the camera on and off when AC power is applied and removed. However, there is no UI to configure this feature right now. This should be added to the Util window as a checkbox.

**Comment by DDR0** [comment]
This feature appears on the Power screen in GUI2, along with a power-off battery level. I agree; it is fine to leave it a checkbox here. :+1:

**Comment by sanjpm** [comment]
Implemented as of v0.3.2
