### ISSUE TITLE
No Batt is intermittently displayed even with battery installed

### ISSUE THREAD

**Issue by skronstein** [krontech/chronos-cam-app#67]
Even with battery installed, No Batt is intermittently displayed in place of the battery % and voltage in the bottom right corner of the main screen.
Forum thread, started in early May: http://forum.krontech.ca/index.php?topic=468.0

**Comment by oskirby** [comment]
I am not able to reproduce this issue, I suspect that the user may have a camera with poorly positioned battery terminals and that it seems to be a hardware problem.

**Comment by oskirby** [comment]
Closing this issue on the assumption that its a hardware fault.
