### ISSUE TITLE
Max Bitrate adjusts max megabits per 60 frames instead of the actual max bitrate

### ISSUE THREAD

**Issue by skronstein** [krontech/chronos-cam-app#74]
If the saved file frame rate is set lower than 60fps, the maximum bitrate will not adjust the max bitrate, but instead the max megabits per 60 frames.

**Comment by skronstein** [comment]
Perhaps either the UI should indicate that this adjusts the max megabits per 60 frames, or the maximum settable UI value for Max Bitrate should be adjusted each time Saved File Framerate is adjusted.
The user manual already somewhat addresses this, as it says the following: "If the saved file frame rate is set lower than 60fps, the maximum bitrate will be lower than 60Mbps."

**Comment by oskirby** [comment]
I think 'maximum megabits per 60 frames' is not a metric that makes a lot of sense and we should fix the UI to display megabits per second correctly.

**Comment by skronstein** [comment]
Fixed: https://github.com/krontech/chronos-cam-app/commit/7fb947e598e40d6548b09cc07fb97e5473ae0ad5
