### ISSUE TITLE
Incorrect TIFF tags produced by monochrome camera

### ISSUE THREAD

**Issue by skronstein** [krontech/chronos-cam-app#81]
The TIFF tags for files saved by a monochrome camera were:
Photometric Interpretation: RGB color
Samples/Pixel: 3

whereas they should be:
Photometric Interpretation: min-is-black
Samples/Pixel: 1

The camera model is correctly shown on the About screen as Monochrome.
[frame_000002.tiff.zip](https://github.com/krontech/chronos-cam-app/files/3503884/frame_000002.tiff.zip)

**Comment by oskirby** [comment]
It seems that this is still occurring even after the latest update.
